module.exports.api = require('./api');
//module.exports.auth = require('./auth');
//module.exports.profiles = require('./profiles');
module.exports.games = require('./games');
module.exports.createGame = require('./createGame');
// module.exports.updateGame = require('./updateGame');
module.exports.addPlayer = require('./addPlayer');
module.exports.dealCards = require('./dealCards');
module.exports.getHand = require('./getHand');
